
#arg variables can be specified at build time as:
#docker build --build-arg user=$USER
ARG user

# base image is ubuntu
# TODO: change to px4io's image
FROM ubuntu

# 1. install sudo first
RUN apt-get update && apt-get install sudo

# 2. use same username as $USER
# arg vars are temporary, so save it in an env variable
ENV env_USER=$user

# add user 
RUN useradd -ms /bin/bash ${env_USER}
RUN usermod -aG sudo ${env_USER}

# change password
# PASSWORD is same as username
RUN echo "${env_USER}:${env_USER}" | sudo chpasswd

# change to user(currently root)
USER ${env_USER}
#set the home directory too 
WORKDIR /home/${env_USER}
